### PR TITLE
fix: module export references should be identifiers

### LINKED ISSUE #218: different AST produced for ModuleExport from wasm / wat parser
Given the following wat:

```
(export "test" (func 1))
```

The WAT parser creates this AST:

```
          {
            "type": "ModuleExport",
            "name": "test",
            "descr": {
              "type": "Func",
              "id": {
               "type": "NumberLiteral",
               "value": 1,
               "raw": "1"
              }
            }
          }
```

However, converting this wat to wasm, via wabt, then parsing with th ewasm-parser, the following AST is generated:

```
          {
            "type": "ModuleExport",
            "name": "test",
            "descr": {
              "type": "Func",
              "id": {
               "type": "Identifier",
               "value": "func_2"
              }
            }
          }
```

Which is correct?

The wasm parser output looks more logical to me!

### PR DESCRIPTION
**Pull request by ColinEberhardt**
fixes #218

### CODE REVIEW

File: packages/webassemblyjs/src/interpreter/runtime/values/module.js [hunk 1]
```diff
@@ -292,39 +292,13 @@ function instantiateExports(
   traverse(n, {
     ModuleExport({ node }: NodePath<ModuleExport>) {
       if (node.descr.type === "Func") {
-        // Referenced by its index in the module.funcaddrs
-        if (node.descr.id.type === "NumberLiteral") {
```
Comment (xtuc) [inline packages/webassemblyjs/src/interpreter/runtime/values/module.js]: Could we maybe throw here? like "internal compiler failure". Because if we get into this it will be very hard to debug.

Comment (ColinEberhardt) [reply packages/webassemblyjs/src/interpreter/runtime/values/module.js]: Yeah, good idea - I've done a slightly more aggressive refactor in https://github.com/xtuc/webassemblyjs/pull/225/commits/942797a8e62e31d594b3dd85d1664d3d789fe9f9 so that all the temporary 'instantiated' items have the same structure. This means I was able add this exception logic in a single place.

File: packages/wast-parser/test/fixtures/export/global/expected.json [hunk 2]
```diff
@@ -37,9 +37,8 @@
           "descr": {
             "type": "Global",
             "id": {
-              "type": "NumberLiteral",
-              "value": 0,
-              "raw": "0"
+              "type": "Identifier",
+              "value": "global_0"
```
Comment (xtuc) [inline packages/wast-parser/test/fixtures/export/global/expected.json]: We should preserve the `raw` value because it will be printed as `global_0` otherwise.

Comment (ColinEberhardt) [reply packages/wast-parser/test/fixtures/export/global/expected.json]: Good point, I presume the raw values are used for round tripping back to wasm / wat?

Comment (xtuc) [reply packages/wast-parser/test/fixtures/export/global/expected.json]: I'm not sure what do you mean by "round tripping back to wasm / wat" but we already have deterministic transformation for Identifier ⟶ Indice and the inverse. We can transform for wasm as well as for wast.

`raw` is just for printing I think.

Comment (ColinEberhardt) [reply packages/wast-parser/test/fixtures/export/global/expected.json]: I think this is a bigger change, so I've pulled it out into this issue for clarification https://github.com/xtuc/webassemblyjs/issues/228
