### PR TITLE
Handle cases where edits change length of LEB encoded byte or vec size

### LINKED ISSUE #407: wasm-edit can trigger LEB128 warning, producing corrupt output
### Description
In some circumstances, wasm-edit can produce corrupt, non-compilable output. These cases appear to coincide with a warning, "LEB128 encoding changed, this might lead to bugs" (generated by [helper-wasm-section](https://github.com/xtuc/webassemblyjs/blob/babd73f8734dea82f8c1e617001f97af09dd2c32/packages/helper-wasm-section/src/resize.js#L42)). 

### Steps to Repro
The behavior depends on the input wasm and the edit(s) applied. [Full repro here](https://github.com/TimHambourger/webassemblyjs-wasm-corruption). Or skip straight to [test results](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/blob/master/webassemblyjs-repro/fullTextResults.txt).

#### Steps to run
1. Clone the linked repo
1. Cd into the webassemblyjs-repro directory
1. Run `npm install`
1. Run `node index.js`

That will read all of the .wasm files in the wasm-input directory and apply a series of edits to each one. For each file + edit combo, the harness then tests if the output is valid WASM by a) parsing w/ wasm-parser and b) compiling w/ V8's native `WebAssembly.compile`. The harness then logs test results to console and writes all output files (valid or not) to the wasm-output directory.

Sample output (excerpted for [single input file](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/blob/master/webassemblyjs-repro/wasm-input/julia_wasm_bg.wasm) and single edit):
```
running case julia_wasm_bg.wasm -- oneCharExports
LEB128 encoding changed, this might lead to bugs
julia_wasm_bg.wasm -- oneCharExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: CompileError: WasmCompile: Wasm decoding failed: unknown section code #0x1f @+786
```

The edit applied (where bin is the input `ArrayBuffer`):
```js
function oneCharExports(bin) {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    let i = 0;
    return editWithAST(getAST(bin), bin, {
        ModuleExport(path) {
            path.node.name = chars[i++];
        }
    });
}

function getAST(bin) {
    return decode(bin, {
        // Needed to work around https://github.com/xtuc/webassemblyjs/issues/405
        ignoreCustomNameSection: true,
        // ignoreDataSection and ignoreCodeSection seem to significantly speed up the decode
        ignoreDataSection: true,
        ignoreCodeSection: true,
    });
}
```

[Results for more files](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/blob/master/webassemblyjs-repro/fullTextResults.txt)

### About the Input Files
I've included several input files (hopefully not an overwhelming number), some of which expose the behavior and some of which don't.

- julia_wasm_bg.wasm -- This is the one I really care about. From a [toy project of mine](https://github.com/TimHambourger/julia-wasm) for trying out WASM + build tools (plus Rust, [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen), [surplus](https://github.com/adamhaile/surplus), fun stuff...). Note that I'm in the middle of switching to webpack's built-in WASM support, hence how I got to webassemblyjs....
- add.wasm, call.wasm -- From [MDN's examples](https://github.com/mdn/webassembly-examples/tree/master/understanding-text-format). These don't trigger the bug.
- Others -- compiled from simple [Rust src](https://github.com/TimHambourger/webassemblyjs-wasm-corruption/tree/master/wasm-src) with various build settings and post-processing steps. I'm happy to provide more detail if it's helpful.

### Observations
The corruption strongly correlates with the LEB128 warning. So far, I haven't found a way to pre-process the failing cases to avoid the warning. Also note a few cases don't trigger the warning but do still fail a wasm-parser `decode` (but not a `WebAssembly.compile`):
```
get37_debug.wasm -- addAssignExports -- FAIL
    wasm-parser error:        Error: invalid UTF-8 encoding
    native WebAssembly error: null
```

### Environment
webassemblyjs packages -- all 1.5.13
node -- 8.9.2
OS -- OSX 10.13.5

Thanks for your help!

### PR DESCRIPTION
**Pull request by TimHambourger**
Fixes #407 (with a few exceptions I'll note on that issue thread). Also fixes a related issue if deleting a node changes the length of the encoded vec size for a section.

### CODE REVIEW

File: packages/wasm-edit/test/handle-resize.js [hunk 1]
```diff
@@ -0,0 +1,183 @@
...
+      [constants.sections.func, 0x02, 0x01, 0x00],
+      [constants.sections.export, ...expSectionSize1, ...expVec1],
+      [constants.sections.code, 0x04, 0x01, 0x02, 0x00, 0x0b]
+    );
+
+    /**
+     * Phase 1. Shorten all export names and compare.
+     */
+
+    // Shortened export names menas 20 exports * 5 bytes per export = 100 bytes.
```
Comment (xtuc) [inline packages/wasm-edit/test/handle-resize.js]: Nit: typo here: means

**Comment by TimHambourger** [comment]
Sweet, thanks! Good catch on the typo.
