### PR TITLE
Fixed cyclic dependencies for production dependencies

### LINKED ISSUE #184: Fix cycle in the dependency graph
It has been introduced by #180 

```
lerna WARN ECYCLE Encountered a cycle in the dependency graph.This may cause instability! Packages in cycle are: "@webassemblyjs/ast", "@webassemblyjs/cli", "@webassemblyjs/dce", "@webassemblyjs/wasm-gen", "@webassemblyjs/wasm-parser", "@webassemblyjs/wast-parser", "@webassemblyjs/wast-printer", "webassemblyjs"
lerna WARN ECYCLE Encountered a cycle in the dependency graph.This may cause instability! Packages in cycle are: "@webassemblyjs/ast", "@webassemblyjs/cli", "@webassemblyjs/dce", "@webassemblyjs/wasm-gen", "@webassemblyjs/wasm-parser", "webassemblyjs"
lerna WARN ECYCLE Encountered a cycle in the dependency graph.This may cause instability! Packages in cycle are: "@webassemblyjs/ast", "@webassemblyjs/cli", "@webassemblyjs/dce", "webassemblyjs"
```

### LINKED ISSUE #382: Remove dependency ast -> wast-parser
We use `@webassemblyjs/wast-parser/lib/number-literals` in ast, maybe we should split the package.

### PR DESCRIPTION
**Pull request by albertcabello**
Fixes #382 
Partially fixes #184 since this is only for the production dependencies and not the devDependencies.

### CODE REVIEW

File: packages/ast/src/nodes.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ export function module(
   const node: Module = {
     type: "Module",
     id,
-    fields
```
Comment (xtuc) [inline packages/ast/src/nodes.js:33]: That file is autogenerated. We could change the generator (`scripts/generateNodeUtils.js`) to fix the style but we can also just ignore that file

File: packages/ast/src/types/nodes.js [hunk 2]
```diff
@@ -96,42 +96,42 @@ type ModuleMetadata = {
   sections: Array<SectionMetadata>,
   functionNames?: Array<FunctionNameMetadata>,
   localNames?: Array<ModuleMetadata>,
-  producers?: Array<ProducersSectionMetadata>
```
Comment (xtuc) [inline packages/ast/src/types/nodes.js:99]: this file is also autogenerated. I suggest we revert the changes

**Review by xtuc — APPROVED** [review]
great, thanks!

**Comment by xtuc** [comment]
I published the versions:
```
Successfully published:
 - @webassemblyjs/ast@1.10.0
 - @webassemblyjs/cli@1.10.0
 - @webassemblyjs/dce@1.10.0
 - eslint-plugin-webassembly@1.10.0
 - @webassemblyjs/floating-point-hex-parser@1.10.0
 - @webassemblyjs/helper-api-error@1.10.0
 - @webassemblyjs/helper-buffer@1.10.0
 - @webassemblyjs/helper-code-frame@1.10.0
 - @webassemblyjs/helper-compiler@1.10.0
 - @webassemblyjs/helper-flatten-ast@1.10.0
 - @webassemblyjs/helper-fsm@1.10.0
 - @webassemblyjs/helper-numbers@1.10.0
 - @webassemblyjs/helper-test-framework@1.10.0
 - @webassemblyjs/helper-testsuite-runner@1.10.0
 - @webassemblyjs/helper-wasm-bytecode@1.10.0
 - @webassemblyjs/helper-wasm-section@1.10.0
 - @webassemblyjs/ieee754@1.10.0
 - @webassemblyjs/leb128@1.10.0
 - @webassemblyjs/repl@1.10.0
 - @webassemblyjs/utf8@1.10.0
 - @webassemblyjs/validation@1.10.0
 - @webassemblyjs/wasm-edit@1.10.0
 - @webassemblyjs/wasm-gen@1.10.0
 - @webassemblyjs/wasm-opt@1.10.0
 - @webassemblyjs/wasm-parser@1.10.0
 - @webassemblyjs/wasm-text-gen@1.10.0
 - wast-loader@1.10.0
 - @webassemblyjs/wast-parser@1.10.0
 - @webassemblyjs/wast-printer@1.10.0
 - @webassemblyjs/wast-refmt@1.10.0
 - webassemblyjs@1.10.0
```

with you change
